language: dart
sudo: required
dist: trusty
dart:
  - stable
  - dev
before_script:
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - idb_sqflite_support/root_travis.sh
