language: dart
sudo: required
dist: trusty
dart:
  - stable
  - dev
before_script:
  - cd idb_sqflite_support/
  - ./before_travis.sh
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - idb_sqflite_support/root_travis.sh
